export { PlannerEngine, planner } from './plannerEngine'
export { defaultPlanningProfile } from './domain/entities/UserPlanningProfile'
export { normalizePlannerTask } from './domain/entities/PlannerTask'
export { fromLegacyTask } from './infrastructure/adapters/LegacyTaskAdapter'
export type { PlannerTask, EnergyRequired } from './domain/entities/PlannerTask'
export type { UserPlanningProfile } from './domain/entities/UserPlanningProfile'
export type { PlanResult, PlanWeekResult, PlannedBlock, BusyBlock, LearningEvent, LearningPattern } from './domain/entities/Planning'
export type { PlanningObservation, UserProductivityPattern, PlanningPreferenceAdjustment, PlanningConflict } from './domain/entities/Planning'
export { calculateTaskScore } from './domain/scoring/TaskScoring'
export type { TaskScoreResult, TaskScoringContext } from './domain/scoring/TaskScoring'
export { DayRescheduler } from './domain/rescheduling/DayRescheduler'
export type { RescheduleComparison, PlanChange } from './domain/rescheduling/DayRescheduler'
export { DeterministicTaskBreakdownProvider } from './domain/services/TaskBreakdownService'
export type { TaskBreakdownProvider, TaskBreakdownProposal } from './domain/services/TaskBreakdownService'
export { ProductivityPatternService } from './domain/learning/ProductivityPatternService'
export type { PlanDayCommand, PlanWeekCommand, RecalculateCommand } from './application/commands/PlannerCommands'
export type { RankTasksQuery } from './application/queries/PlannerQueries'
